### ISSUE TITLE
Optionally dereference symlinks

### ISSUE THREAD

**Issue by probonopd** [CalebQ42/squashfs#1]
Thanks @CalebQ42 for this extremely useful library.

When I wrote go-appimage, one area that I would have loved to have is the option to follow (dereference) symlinks when extracting from squashfs. Sometimes want to extract the symlinks as such, sometimes you want to extract the files/directories they point to.

I think the go-appimage code could be significantly cleaned up if this capability could become part of this library.

**Comment by CalebQ42** [comment]
That's definitely something I could do. It probably wouldn't be too difficult to add something like file.ExtractSymlink with the option to extract just the symlink, or extract what the symlink is pointing to.

**Comment by probonopd** [comment]
Related:
https://github.com/plougher/squashfs-tools/issues/77

**Comment by probonopd** [comment]
Thanks for implementing this.

We should make use of it in these places:
https://github.com/probonopd/go-appimage/search?q=symlinks
