### ISSUE TITLE
Open fails with "[" filename

### ISSUE THREAD

**Issue by tri-adam** [CalebQ42/squashfs#10]
I'm getting an error when calling [Open](https://pkg.go.dev/github.com/CalebQ42/squashfs?utm_source=gopls#FS.Open) on a path obtained while running a [WalkDir](https://pkg.go.dev/io/fs#WalkDir) on an [squashfs.FS](https://pkg.go.dev/github.com/CalebQ42/squashfs#FS). The path in question is a tad odd, namely, `bin/[`, but is otherwise unremarkable.

Having traced through the code, I think the problem is here:

https://github.com/CalebQ42/squashfs/blob/6ada4f3b493218e37424bb7faafe7e47791718e6/reader_fs.go#L53

At this point in the code, `path.Match("[", "[")` ends up being called, but this returns _false_ for a match. I believe this is because `[` is treated as a special character in [Match](https://pkg.go.dev/path#Match). A direct check for equality may be more appropriate here? I will open a PR shortly with that for review.

**Comment by CalebQ42** [comment]
I'll have to do some research into this to see what the "correct" implementation for fs.FS is. As it stands I'm hesitant to change it, as I specifically used path.Match to allow for wildcards, and changing it to a direct comparison will break that.

**Comment by tri-adam** [comment]
Wow, thank you for the quick response @CalebQ42. Great module!
