### ISSUE TITLE
go-lzo license is GPL-2.0

### ISSUE THREAD

**Issue by wagoodman** [CalebQ42/squashfs#12]
This library is declared as MIT, however, depends on a library (statically) with a GPL-2.0 license (github.com/rasky/go-lzo). How much of a problem is this? I'm not certain... I'm not a lawyer 😄 . But, this is really easy to miss and and wanted to make certain you were aware of this.

(squashfs is awesome btw ❤️ !)

**Comment by CalebQ42** [comment]
I also am not a lawyer, lol. From what I've researched it isn't much of a problem. The MIT license is "compatible" with GPL. The only caveat being that any released binaries would be licensed under GPL-2.0.

(Thanks for the kind words ❤️!)

**Comment by afbjorklund** [comment]
You might want to have go build tags for the obsolete compressions (such as lzo and xz), so that they can be compiled out.

For LZO, a simple option would be to fork `lzop` instead of linking with the GPL code. Then it becomes a runtime issue only?
