### ISSUE TITLE
Error Opening fragmented files

### ISSUE THREAD

**Issue by tri-adam** [CalebQ42/squashfs#14]
Hi @CalebQ42, thanks again for the great module!

I'm troubleshooting an issue with Anchore Syft (https://github.com/anchore/syft/issues/1150) via its underlying `stereoscope` module (https://github.com/anchore/stereoscope/issues/140), which is a consumer of version 0.5.4 of this module. The issue seems to present itself on `Open` is called on an inode that references a fragment block. At the user level, this manifests itself as an error being returned from `Open`. In the specific example referenced by https://github.com/anchore/syft/issues/1150, the error is:

```
open opt/intel/oneapi/compiler/2022.1.0/linux/lib/oclfpga/host/linux64/bin/perl/lib/5.30.3/pod/perlpod.pod: unexpected EOF
```

Having immersed myself in your code as well as https://dr-emann.github.io/squashfs/squashfs.html, I believe I've identified a few issues with fragment handling. I'll open a PR shortly with patches that seem to fix the issue.

Thanks!

**Comment by CalebQ42** [comment]
There's still something not quite right with fragments. I remade my test squashfs with `-always-use-fragments` and now wrong fragments are being read pretty consistently. I'm going to have to look into this further to see what exactly is going on.

**Comment by CalebQ42** [comment]
Okay, go that sorted. I forgot that some of the decompression readers won't read past a certain amount, so I have to loop it until I get to the correct offset. Anyway, v0.6.1 will be up shortly with the fixes.

**Comment by tri-adam** [comment]
Thanks @CalebQ42! 🙌
