### ISSUE TITLE
Wrong path separator used while reading the squashfs?

### ISSUE THREAD

**Issue by HsuJv** [CalebQ42/squashfs#26]
Hi there,

Thanks for your nifty library and it's been a real help for me.

But I've got something wrong when reading the squashfs on Windows hosts.

After some investigation, it seems line 55 here

https://github.com/CalebQ42/squashfs/blob/54d193a3df985eb6fb4826b1689d4495887946eb/reader_fs.go#L43-L60

shall be altered to 

```Go
	split := strings.Split(name, string(os.PathSeparator))
```

When running on Windows, a `path separator` will be modified to `\` after `filepath.Clean` even if it was passed with `/`
So I think it's better to split its path by os specified separator rather than hardcoding `/`

What do you think?

BRs.

**Comment by CalebQ42** [comment]
So I'd be interested to know your use case as I don't believe I've heard of a squashfs archive being used outside of Linux and Mac. That being said, making the proposed change could cause issues; in particular symlinks are stored with the path separators, which will always (as far as I've seen) use Unix separators. It also wouldn't be just this function, but it would need to be changed in a dozen or so places.

**Comment by HsuJv** [comment]
I'm packing some asset files used by my program with a squashfs. For example, some xmls, some pngs, some mp4s that I don't want to embed directly into my binary.
The compile environment would definitely be on Linux but it can cross-compile different sore of binaries for different platforms, and all using the same squashfs to read its required resource.
