### ISSUE TITLE
Recursively read all files info included in a squashfs filesystem

### ISSUE THREAD

**Issue by ZiqianXu** [CalebQ42/squashfs#29]
Hi @CalebQ42,

Thanks for implementing this handy library, it's been a real help for us.

Is there a function to iterate over all included files in the squashfs filesystem recursively to get all included file info?

Thanks!

**Comment by CalebQ42** [comment]
No, there isn't, but since it implements `fs.FS` you can use [https://pkg.go.dev/io/fs#WalkDir](`fs.WalkDir`) for that functionality.

**Comment by CalebQ42** [comment]
Let me know if you think there would be a benefit to implementing this in library, but I think for _most_ use cases, `fs.WalkDir` is good enough.
